### ISSUE TITLE
Setting Up Environment to Run NVDS Successfully

### ISSUE THREAD

**Issue by TouqeerAhmad** [RaymondWang987/NVDS#10]
I have looked at other issues and running NVDS successfully seems to be a challenge at the moment. I am stating my steps here in hope that someone can advise me to make corrections if I am making any mistakes. 

I am using a conda environment on a Ubuntu 18.04.6 LTS

Here are my steps: 

`conda create --name NVDS_attempt4 python=3.8`
`conda activate NVDS_attempt4`
`conda install pytorch torchvision -c pytorch`

Following the author's advised strict instructions for mmcv/mmseg:

`pip install -U openmim`
`mim install mmengine`
`mim install "mmcv>=2.0.0"`
`pip install "mmsegmentation>=1.0.0"`

At this point, I tried running the code using following instruction:

`CUDA_VISIBLE_DEVICES=0 python infer_NVDS_midas_bi.py --base_dir ./demo_outputs/midas_init/market_6/ --vnum market_6 --infer_w 896 --infer_h 384`

It complained about timm being missing, which I installed next: 

`pip install timm`

And now, I see the following issue. 

"ImportError: /home/touqeera/mambaforge/envs/NVDS_attempt4/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs"

I have tried several times and have not been successful so far in setting up the environment to NVDS' liking. Please advise.

**Comment by RaymondWang987** [comment]
> I have looked at other issues and running NVDS successfully seems to be a challenge at the moment. I am stating my steps here in hope that someone can advise me to make corrections if I am making any mistakes.
> 
> I am using a conda environment on a Ubuntu 18.04.6 LTS
> 
> Here are my steps:
> 
> `conda create --name NVDS_attempt4 python=3.8` `conda activate NVDS_attempt4` `conda install pytorch torchvision -c pytorch`
> 
> Following the author's advised strict instructions for mmcv/mmseg:
> 
> `pip install -U openmim` `mim install mmengine` `mim install "mmcv>=2.0.0"` `pip install "mmsegmentation>=1.0.0"`
> 
> At this point, I tried running the code using following instruction:
> 
> `CUDA_VISIBLE_DEVICES=0 python infer_NVDS_midas_bi.py --base_dir ./demo_outputs/midas_init/market_6/ --vnum market_6 --infer_w 896 --infer_h 384`
> 
> It complained about timm being missing, which I installed next:
> 
> `pip install timm`
> 
> And now, I see the following issue.
> 
> "ImportError: /home/touqeera/mambaforge/envs/NVDS_attempt4/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs"
> 
> I have tried several times and have not been successful so far in setting up the environment to NVDS' liking. Please advise.

Please refer to the answers in [Issue #1](https://github.com/RaymondWang987/NVDS/issues/1).
