### ISSUE TITLE
about training code

### ISSUE THREAD

**Issue by astro-fits** [RaymondWang987/NVDS#3]
A Great Work !
Is there any plan to release training code ?

**Comment by RaymondWang987** [comment]
> A Great Work !
> Is there any plan to release training code ?

Hi! Thanks for your interest in our work. For now, we do not plan to release our training code. In the future, we might consider organizing and releasing the training scripts (e.g., training on VDW or finetuning on NYUDV2).

**Comment by astro-fits** [comment]
Thank you for your reply.
